In [1]:
a = [1,2,3,4]


In [2]:
a


[1, 2, 3, 4]

In [3]:
a+1

TypeError: can only concatenate list (not "int") to list

In [4]:
import numpy as np

a = np.array([1,2,3,4])


In [5]:
a+1

array([2, 3, 4, 5])

In [6]:
a**2

array([ 1,  4,  9, 16])

In [7]:
b = np.ones(4) + 1

In [8]:
b

array([2., 2., 2., 2.])

In [18]:
a - b

array([-1.,  0.,  1.,  2.])

In [19]:
a * b

array([2., 4., 6., 8.])

### array multiplication

In [13]:
c = np.diag([1,2,3,4])

In [17]:
print(c*c*c)

[[ 1  0  0  0]
 [ 0  8  0  0]
 [ 0  0 27  0]
 [ 0  0  0 64]]


In [20]:
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [22]:
c = [1,2,3,4]
d = [5,6,7,8]

c == d

False

In [23]:
p = np.array([1,2,3,4])
q = np.array([2,3,3,4])

In [24]:
p == q

array([False, False,  True,  True])